name: Publish

on:
  release:
    types: [published]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm i -g codecov
      - run: npm run lint
      - run: npm run test:single
      - run: npm run test:check-coverage
      - run: cat ./coverage/lcov.info | codecov
        env:
          CODECOV_TOKEN: ${{secrets.codecov_token}}

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get package version
        uses: actions/github-script@0.2.0
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Publish package
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        run: npm ci
        run: npm version ${{steps.get_version.outputs.VERSION}}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
